const path = require("path");
const fs = require("fs");
const alemPkg = require("../../package.json");

const addSignatures = (bundleContent) => {
  const projectPkg = JSON.parse(
    fs.readFileSync(path.join("package.json"), "utf-8"),
  );

  const projectRepositoryLink =
    projectPkg?.repository && typeof projectPkg?.repository === "string"
      ? projectPkg?.repository
      : projectPkg.repository?.url || "";

  bundleContent = `
  /** Bundle generated by Além Library v${alemPkg.version} - See more here: https://github.com/wpdas/alem */
  ${projectRepositoryLink ? `/** Project repository: ${projectRepositoryLink.replaceAll("git+", "").replaceAll(".git", "")} */` : ""}
  ${bundleContent}
  `;

  return bundleContent;
};

module.exports = addSignatures;
